services:
  frontend:
    container_name: mlb_frontend_prod
    environment:
      - APP_ENV=production
      - DEV_URL=http://localhost:3000
      - PROD_URL=http://localhost:3001
    ports:
      - "3001:3000"
    labels:
      - "environment=production"

  engine:
    container_name: mlb_engine_prod
    labels:
      - "environment=production"
