services:
  engine:
    restart: always
    labels:
      - "environment=production"

  frontend:
    restart: always
    environment:
      - APP_ENV=production
    labels:
      - "environment=production"

  db:
    restart: always

  redis:
    restart: always
